target_parameters:
  targeted: false
  auto_generate_target: true
  target_images_config:
    target_images_dir:
  target_labels_config:
    target_labels: []
    target_labels_path:
    target_labels_separator: ','
attack_parameters:
  epsilon: 0.3
